name: deploy
on:
  push:
    branches: [development]

jobs:
  deploy_dbt_models:
    name: deploy_dbt_models
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: check out
        uses: actions/checkout@master
      
      - name: setup environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/731312910056/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'dbt-test@noted-tesla-302415.iam.gserviceaccount.com'             

      - name: run dbt
        run: |
          echo "installing dependencies"
          make poetry

          echo "installing dbt"
          pip install dbt-bigquery

          echo "executing DBT models"
          make run_dbt

          echo "running tests"
          make run_dq_tests

          echo "running catalog server"
          make run_catalog_server