name: pre commit checks
on:
  pull_request:
    branches: [development]

jobs:
  pr_to_dev:
    name: pr_to_dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: check out
        uses: actions/checkout@master
      
      - name: setup environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      
      - id: file_changes
        name: changed files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/731312910056/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'dbt-test@noted-tesla-302415.iam.gserviceaccount.com'             

      - name: pre commit check
        run: |
          echo "installing dependencies"
          make poetry

          echo "installing pre-commit"
          make precommit

          echo "installing dbt"
          pip install dbt-bigquery

          echo "Running checks"
          pre-commit run --files ${{steps.file_changes.outputs.files}} 